### PR TITLE
Use @Singleton again

### PR DESCRIPTION
**Pull request by SentryMan**
- uses @Component only if Avaje is on the classpath
- uses Jakarta/javax @Singleton depending on classpath
- uses Jakarta @Singleton by default if both jakarta and javax on classpath
- adds a compiler arg to force javax

### CODE REVIEW

**Comment by rbygrave** [comment]
Yeah, I don't think this is the best approach.  We ideally have 4 cases to support.

- using avaje-inject Jakarta (ignoring javax)
- using avaje-inject javax (ignoring Jakarta)
- using some other DI via Jakarta 
- using some other DI via javax

As an alternative approach, it can detect avaje-inject and then failing that detect Jakarta or javax.

**Comment by SentryMan** [comment]
I can easily add the avaje detection and use @Component for those cases. But for scenrio 3 and 4, I think defaulting to jakarta unless specified is the way to go. Consider the scenario where javax/jakarta just happens to be on the classpath because of a transitive dependency. How should the processor proceed? A flag makes it simple.

**Comment by SentryMan** [comment]
@rbygrave how about this? 

Will use avaje if it's there. Otherwise will use either jakarta/javax on the classpath. If both are on the classpath, will default to jakarta, unless overridden by the flag.

**Review by rbygrave — APPROVED** [review]
Yup, excellent.

**Pull request merged**
