### PR TITLE
Javax Validator Auto Provide

### PR DESCRIPTION
**Pull request by SentryMan**
javax I guess, should we even merge this?

### CODE REVIEW

**Comment by rbygrave** [comment]
I can pull it locally and release it from there without merging it into master.  

I'll comment back into here when I've done that.

**Comment by SentryMan** [comment]
the jakarta one is still not on mvn central

**Comment by SentryMan** [comment]
hmm wait a minute, on my local it doesn't work

**Comment by SentryMan** [comment]
did we get this pushed?

**Comment by rbygrave** [comment]
> did we get this pushed?

No, I've just done it now ... so version 2.9 is on it's way to maven central now.

**Pull request closed without merging**
