### PR TITLE
Update Jex Generation

### PR DESCRIPTION
**Pull request by SentryMan**
- Generates code for the new version of Jex
- adds OPTIONS HTTP annotation

### CODE REVIEW

**Comment by SentryMan** [comment]
@rbygrave should be good to go now

**Comment by rbygrave** [comment]
Yeah. I think the only issue is that the Java 17 build is broken due to it depending on jex generator that is Java 21+ only now right?

**Comment by SentryMan** [comment]
yeah that's the reason

**Comment by rbygrave** [comment]
So remove that dependency or make test-client-generation a Java 21+ only test ?

**Review by rbygrave — APPROVED** [review]

**Pull request merged**
